### ISSUE TITLE
Raspberry Pi

### ISSUE THREAD

**Issue by aussiecrawl** [UnfinishedBusiness/ncPilot#2]
Hi, Just wondering if this will run on a Pi3b or would it be better on a Laptop. I have tried installing these on a Pi, and when i run the make file i get a linuxcnc error, do i need to install Linuxcnc for this to work.

**Comment by UnfinishedBusiness** [comment]
Hey aussicrawl,

I have not tried to run it on Pi3b but if the gpu is fairly good and OpenGL works then I don’t see why it wouldn’t. 

So ncPilot doesn’t have anything to do with LinuxCNC so I’m confused as to why it would say something about that. Could you attach a screenshot of the error?

ncPilot is the interface for my XmotionFirmware repo. It’s a fork of GRBL with AVTHC added in for plasma cutting and also a whole bunch of other features (like inline CRC during gcode stream with serial error detection) that makes the system stable in electrically noisy environments. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by aussiecrawl** [comment]
Hey thanks for the response.

I have no idea but i think the Pi was about to die which it now has. So im using my laptop, but im still having trouble getting NcPilot to run or do anything. I have both the XmotionFirmware flahed onto the Arduino and download the ncPilot but can get anything to open or run from ncPilot. 

Would it be possible for you to write out a basic How to get started steps to get this up and running.

**Comment by UnfinishedBusiness** [comment]
Hey, no problem.

I just added build instructions [here](https://github.com/UnfinishedBusiness/Xkernel/blob/master/README.md) for Xkernel.

I recommend cloning Xkernel and ncPliot in the same upper directory.
This way you can start ncPilot by for example "cd /c/Xmotion/ncPilot" and then "../Xkernel/Xkernel src/main.js"

There is also run_no_console.vbs in the ncPilot repo that will start ncPilot by double clicking and expects the Xkernel binary to be at the relative path ../Xkernel/Xkernel. You can right-click and make a shortcut of that file on your desktop.

**Comment by aussiecrawl** [comment]
Hey,
thanks for the build instructions. Im still having problems getting this to work when i try and run the run_no_console.vbs im getting the following errors

/c/Xkernel/ncPilot/run_no_console.vbs: line 1: syntax error near unexpected token `C'
/c/Xkernel/ncPilot/run_no_console.vbs: line 1 `set oshell = CreateObject ( "Wscript.shell" )'

**Comment by UnfinishedBusiness** [comment]
Hey,

So I’m going to edit the build instructions so they are more clear tomorrow for you. 

Your directory structures should be as follows 
/c/Xmotion
/c/Xmotion/ncPilot
/c/Xmotion/Xkernel

It looks like you cloned ncPilot repo inside the Xkernel directory. Fix the directory structure and you should be in good shape as long as Xkernel built fine

**Comment by aussiecrawl** [comment]
Hi thanks for the help.

I changed the directory structure to be the same as above and ncpilot works.

With the Xmotion firmware im now getting a compile error when trying to get Xmotion onto the Arduino. I had previously flashed the standard Grbl 0.9 on to it. Im getting the following error now

In file included from C:\Users\david\Documents\Arduino\libraries\src/config.h:30:0,

                 from C:\Users\david\Documents\Arduino\sketch_mar22a\sketch_mar22a.ino:1:

C:\Users\david\Documents\Arduino\libraries\src/grbl.h:83:4: error: #error "Required HOMING_CYCLE_0 not defined."

   #error "Required HOMING_CYCLE_0 not defined."

    ^~~~~

C:\Users\david\Documents\Arduino\libraries\src/grbl.h:123:4: error: #error "WCO refresh must be greater than one."

   #error "WCO refresh must be greater than one."

    ^~~~~

C:\Users\david\Documents\Arduino\libraries\src/grbl.h:126:4: error: #error "Override refresh must be greater than zero."

   #error "Override refresh must be greater than zero."

    ^~~~~

exit status 1
Error compiling for board Arduino Uno.

**Comment by UnfinishedBusiness** [comment]
Hey, no worries.

So I have not tried compiling XmotionFirmware with Arduino IDE. I've done all my development with Visual Studio Code IDE with PlatformIO plugin. The repo already has the platformio setup ini file so if you install code studio and the PlatformIO plugin you can compile and upload the firmware in a snap.

As an alternative to you compiling the firmware, i've included a firmware.hex binary in the ncPilot repo. You can install the firmware via avrdude. Open MSYS2 and cd /Xmotion/ncPilot/extra

Then make sure avrdude is installed via pacman, if it's not install it...

Then use ncPilot/extra/flash.sh COM4 (or whatever com port your arduino uno is on) and it will flash the firmware onto it.

**Comment by UnfinishedBusiness** [comment]
@aussiecrawl - Did you get this up and running okay?
