### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by cadrion77** [UnfinishedBusiness/ncPilot#6]
Hi there...

I was trying to get this setup on a laptop that I have.  Just put a fresh copy of 10 on it and got it all setup.  went through the instructions and when I try to run ncPilot, I see the led flash on the arduino then gives a segmentation fault.  Any idea what this is?  The board works and connects fine on my main pc..

thanks for the help

**Comment by UnfinishedBusiness** [comment]
Hello,

I'm not sure but the version of ncPilot that runs via the Xkernel VM is being phased out. Xkernel served it's purpose and allowed me to rapidly develop ncPilot (and a few other programs we needed) but now I have created a header based C/C++ library that packs all the features Xkernel provided. The biggest problem I was having with Xkernel was memory management with the Duktape library (the Javascripting interface) not collecting garbage correctly which would eventually eat all available heap and kill the program.

I'll be updating the main branch very soon with the new version of ncPilot which does not require Xkernel and is very stable. There will also be binary builds for Mac, Linux, and Windows...

Thanks,
Travis
