### ISSUE TITLE
Stand alone version not working

### ISSUE THREAD

**Issue by cadrion77** [UnfinishedBusiness/ncPilot#7]
Hi there, 

I have been able to figure out how to get the stand alone version built and communicating on a rpi 4.  I have found something though- I have an official Uno and it works fine- gets detected no prob.  I have my GRBL board that has a CH341 serial chip rather than FTDI and it gets detected but hangs on the found device line running it as ./ncpilot, no com lights.  When I run the official, it does the found device then open port and goes on to run, com lights flashing.  The other one doesn't look like it crashes, its like it's waiting for something.   I can get the same GRBL board to communicate and work on the Xkernal version ok.   Any ideas?

**Comment by UnfinishedBusiness** [comment]
I responded a bit ago to your other issue. The dev branch is highly unstable at the moment. I have a private repository on a different platform where I have been developing the stand-alone version. Soon, I'll be updating the main branch with the stand-alone version I've been developing in a private repository. Currently it has a CAM workbench that works a lot like sheetcam and is very stable. My development goals for ncPilot in the future is to add design functionality like lightburn for laser cutters so users can design and cut in one place but also have more traditional CAD tools as well.
