### ISSUE TITLE
Scale units and font size

### ISSUE THREAD

**Issue by klandrith** [UnfinishedBusiness/ncPilot#8]
First off thank you for the contribution of this software and firmware for the Arduino. Two issues here.

1. How do you set the scale units? The machine parameters window says to set scales to desired units, but there is nowhere to do so.
2. Without manually sorting through the code base, where might I find the font size so that I can modify it and recompile with a bigger font size for some items.

Thank you.

**Comment by UnfinishedBusiness** [comment]
Sorry for getting back late. 

1. The units are in steps / unit. So if you want to work in MM, set your step scale to however many steps are in on MM, if you want to work in Inch, set your step scale to the number of steps that correlate to 1" of travel.

2. To set the font you need to bring an TTF file. Add the following to EasyRender.cpp @ line 754

/*Custom IMGUI Font and Size*/
this->imgui_io->Fonts->AddFontFromFileTTF("font.ttf", 20);

You can change "font.ttf" to the path of your ttf file or just make sure "font.ttf" is in the working directory that you execute from. 20 is the font height in pixels

Also, as an FYI, I've sold ncPilot and the rights to it to an Australian OEM, [Promach](https://promach.com.au). They'll be branding ncPilot and advancing it on their end privately. What I have here is going to be archived and still available but I will no longer be developing it any further.
